ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(80) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_object_key VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_mime_type VARCHAR(80) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_size INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS avatar_updated_at TIMESTAMPTZ;
