ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_object_key VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_size INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
    DROP COLUMN IF EXISTS avatar_data;
